/**
 * Reads one of the vendored per-Surah text files under public/ (generated by the scripts in
 * scripts/). Translations and tafsir both live there rather than in the bundle: their Tabs are
 * opened at runtime, so their text is fetched on demand.
 *
 * `description` names what is being read, in a form that reads as the subject of a sentence.
 */
export async function fetchAyahTexts(
  path: string,
  description: string,
): Promise<readonly string[]> {
  // The path is browser-relative, so this only resolves in a browser. Say so loudly: prerendering
  // a Tab would otherwise stall the static export on a request that cannot complete.
  if (typeof window === "undefined") {
    throw new Error(`${description} loads in the browser; it cannot be read while prerendering`);
  }

  const response = await fetch(path);
  if (!response.ok) throw new Error(`Could not load ${description}`);

  return (await response.json()) as readonly string[];
}
