import { fetchAyahTexts } from "./content-fetch";
import type { TafsirTextLoader } from "./quran-content-repository";

// Generated by scripts/vendor-tafsir.mjs.
const TAFSIR_BASE_PATH = "/content/tafsir";

export const fetchTafsirText: TafsirTextLoader = (surahNumber, source, language) =>
  fetchAyahTexts(
    `${TAFSIR_BASE_PATH}/${source}/${language}/${surahNumber}.json`,
    `the ${language} ${source} tafsir of Surah ${surahNumber}`,
  );
