import type { TranslationTextLoader } from "./quran-content-repository";

// Translations live under public/ (generated by scripts/vendor-translations.mjs) rather than in
// the bundle: a Translation Tab is opened at runtime, so its text is fetched on demand.
const TRANSLATIONS_BASE_PATH = "/content/translations";

export const fetchTranslationText: TranslationTextLoader = async (surahNumber, language) => {
  // The path is browser-relative, so this only resolves in a browser. Say so loudly: prerendering
  // a Translation Tab would otherwise stall the static export on a request that cannot complete.
  if (typeof window === "undefined") {
    throw new Error("Translations load in the browser; they cannot be read while prerendering");
  }

  const response = await fetch(`${TRANSLATIONS_BASE_PATH}/${language}/${surahNumber}.json`);
  if (!response.ok) {
    throw new Error(`Could not load the ${language} translation of Surah ${surahNumber}`);
  }

  return (await response.json()) as readonly string[];
};
