import { fetchAyahTexts } from "./content-fetch";
import type { TranslationTextLoader } from "./quran-content-repository";

// Generated by scripts/vendor-translations.mjs.
const TRANSLATIONS_BASE_PATH = "/content/translations";

export const fetchTranslationText: TranslationTextLoader = (surahNumber, language) =>
  fetchAyahTexts(
    `${TRANSLATIONS_BASE_PATH}/${language}/${surahNumber}.json`,
    `the ${language} translation of Surah ${surahNumber}`,
  );
