import { fetchAyahTexts } from "./content-fetch";
import type { TransliterationTextLoader } from "./quran-content-repository";

// Generated by scripts/vendor-transliteration.mjs. Fetched rather than bundled with the Arabic —
// three schemes at ~1 MB each, of which a reader reads one: docs/adr/0005-transliteration-as-fetched-corpus.md.
//
// Nothing indexes this. The Retrieval Index is built over the translations and tafsir only
// (scripts/build-retrieval-index.mjs); a Transliteration is phonetic rather than meaning-bearing,
// so it could only match a question that happened to share Latin spellings.
const TRANSLITERATION_BASE_PATH = "/content/transliteration";

export const fetchTransliterationText: TransliterationTextLoader = (surahNumber, scheme) =>
  fetchAyahTexts(
    `${TRANSLITERATION_BASE_PATH}/${scheme}/${surahNumber}.json`,
    `the ${scheme} transliteration of Surah ${surahNumber}`,
  );
