import { quranContent } from "@/content/bundled-quran";
import { fetchContent } from "@/content/content-fetch";
import { TAFSIR_SOURCES, type TranslationLanguage } from "@/content/quran";
import { createCorpusRetriever } from "./corpus-retriever";
import type { PassageRef, RetrievalIndex } from "./retrieval-index";

// Generated by scripts/build-retrieval-index.mjs.
const RETRIEVAL_BASE_PATH = "/content/retrieval";

/**
 * The index says a passage is tafsir, not which tafsir — there is one source in the corpus, so
 * naming it would be a field with one value in every one of 12,000 entries. Adding a second source
 * means teaching the index to tell them apart; this is where that shows up as a lie.
 */
const [ONLY_TAFSIR_SOURCE] = TAFSIR_SOURCES;

const loadIndex = (language: TranslationLanguage) =>
  fetchContent<RetrievalIndex>(
    `${RETRIEVAL_BASE_PATH}/${language}.json`,
    `the ${language} Retrieval Index`,
  );

const ayahText = (
  texts: readonly { text: string }[],
  { ref, kind }: PassageRef,
): string => {
  const found = texts[ref.ayah - 1];
  // An index built against a corpus the app no longer ships. Retrieval drops the passage rather
  // than the question, so this reaches the reader as one fewer passage, never as a failure.
  if (!found) throw new RangeError(`No ${kind} for Ayah ${ref.surah}:${ref.ayah}`);
  return found.text;
};

/**
 * Retrieval as the browser does it: the shard fetched from public/, and the passages' own text
 * read back through the content repository the Tabs already read it through — so a passage the
 * reader is shown a citation of is the same text their Translation or Tafsir Tab would show.
 */
export const corpusRetriever = createCorpusRetriever({
  loadIndex,
  async readPassage(passage, language) {
    if (passage.kind === "translation") {
      const translation = await quranContent.getTranslation(passage.ref.surah, language);
      if (!translation.available) {
        throw new RangeError(`No translation in ${language} to retrieve from`);
      }
      return ayahText(translation.ayahs, passage);
    }

    const tafsir = await quranContent.getTafsir(passage.ref.surah, ONLY_TAFSIR_SOURCE, language);
    if (!tafsir.available) throw new RangeError(`No tafsir in ${language} to retrieve from`);

    return ayahText(tafsir.ayahs, passage);
  },
});
